// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SentimentModel_ConsoleApp1
{
    public partial class SentimentModel
    {
        /// <summary>
        /// model input class for SentimentModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"QiShu")]
            public float QiShu { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"AAA001")]
            public float AAA001 { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"AAA002")]
            public float AAA002 { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"AAA003")]
            public float AAA003 { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"AAA004")]
            public float AAA004 { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"AAA005")]
            public float AAA005 { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"AAA006")]
            public float AAA006 { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"AAE001")]
            public float AAE001 { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Year")]
            public float Year { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SentimentModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"QiShu")]
            public float QiShu { get; set; }

            [ColumnName(@"AAA001")]
            public uint AAA001 { get; set; }

            [ColumnName(@"AAA002")]
            public float AAA002 { get; set; }

            [ColumnName(@"AAA003")]
            public float AAA003 { get; set; }

            [ColumnName(@"AAA004")]
            public float AAA004 { get; set; }

            [ColumnName(@"AAA005")]
            public float AAA005 { get; set; }

            [ColumnName(@"AAA006")]
            public float AAA006 { get; set; }

            [ColumnName(@"AAE001")]
            public float AAE001 { get; set; }

            [ColumnName(@"Year")]
            public float Year { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SentimentModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
