
// This file was auto-generated by ML.NET Model Builder. 

using SentimentModel_ConsoleApp3;

// Create single instance of sample data from first line of dataset for model input
SentimentModel.ModelInput sampleData = new SentimentModel.ModelInput()
{
    QiShu = 2023013F,
    AAA001 = 6F,
    AAA002 = 10F,
    AAA003 = 14F,
    AAA004 = 22F,
    AAA005 = 23F,
    AAA006 = 33F,
    Year = 2023F,
};

// Make a single prediction on the sample data and print results
var predictionResult = SentimentModel.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual AAE001 with predicted AAE001 from sample data...\n\n");


Console.WriteLine($"QiShu: {2023013F}");
Console.WriteLine($"AAA001: {6F}");
Console.WriteLine($"AAA002: {10F}");
Console.WriteLine($"AAA003: {14F}");
Console.WriteLine($"AAA004: {22F}");
Console.WriteLine($"AAA005: {23F}");
Console.WriteLine($"AAA006: {33F}");
Console.WriteLine($"AAE001: {13F}");
Console.WriteLine($"Year: {2023F}");


Console.WriteLine($"\n\nPredicted AAE001: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

